### ISSUE TITLE
ncol(countData) == nrow(colData) is not TRUE

### ISSUE THREAD

**Issue by paulaberry** [SGDDNB/translational_regulation#3]
I have prepared input files and count matrices according to the supplementary protocol, however, I keep getting this error:

```
Error in DESeqDataSetFromMatrix(countData = merge, colData = coldata,  :
  ncol(countData) == nrow(colData) is not TRUE
Calls: DESeqDataSetFromMatrix -> stopifnot
Execution halted
```

The input command I used is `$ Rscript --vanilla ../translational_regulation/DTEG.R ribo_counts.txt rna_counts.txt sample_info.txt 1` and I have attached the input files. Do you know what could be causing this error?
[sample_info.txt](https://github.com/SGDDNB/translational_regulation/files/6641024/sample_info.txt)
[ribo_counts.txt](https://github.com/SGDDNB/translational_regulation/files/6641025/ribo_counts.txt)
[rna_counts.txt](https://github.com/SGDDNB/translational_regulation/files/6641026/rna_counts.txt)

**Comment by soniachothani** [comment]
Hi Paula, 

The script requires the sample_info.txt file to list samples in the same order as in the count matrices of Ribo-seq followed by RNA-seq. So, I would reorder the rows in sample_info.txt file such as the samples are listed in this order based on your count files: SRR1910731, SRR1910732, SRR1910735, SRR1910736, SRR1910733, SRR1910734, SRR1910737, SRR1910738.

Hope this helps, do let me know if it works after re-ordering!

Thanks,
Sonia

**Comment by paulaberry** [comment]
Unfortunately I'm still getting the same output after re-ordering and manually redoing the tabs (it looks like some of the outputs from featureCounts used spaces instead of tabs on the count matrices.) I've copied the full output to the attached text file so you can see where in the process it is stopping. After digging a little into the R script it seems like it might be related to the script using cbind instead of merge so there's two identical columns with Gene IDs?
[deltaTEoutput.txt](https://github.com/SGDDNB/translational_regulation/files/6648977/deltaTEoutput.txt)

**Comment by soniachothani** [comment]
Hey Paula,

I believe the spaces is one of the reasons for the issue. 
Can you try these two edits to your count files: 
1) Remove the "gene_id" text from the ribo_counts.txt and rna_counts.txt file headers. Check https://github.com/SGDDNB/translational_regulation/blob/master/sample_data/ribo_counts.txt
https://github.com/SGDDNB/translational_regulation/blob/master/sample_data/rna_counts.txt
2) sed 's/ /\t/g' ribo_counts.txt > ribo_counts_tab.txt
 sed 's/ /\t/g' rna_counts.txt > rna_counts_tab.txt

Hope it works now, let me know. :)

Best,
Sonia

**Comment by paulaberry** [comment]
I wonder why featureCounts output the file with spaces instead of tabs - reading through their documentation it seems like the expected behavior would be to output with tabs. Anyways, by taking out the gene_id column header the script now executes until hitting a snag past this spot. I will open a new issue for that and close this one.
