### ISSUE TITLE
Results clarification

### ISSUE THREAD

**Issue by agoldkamp** [SGDDNB/translational_regulation#6]
Hello,

I have a question about making sure that I am interpreting the results correctly. 
If we are using the command:
res = results(ddsMat, name="Condition2.SeqTypeRIBO")

Then, the result table shows DTEGs that are downregulated/upregulated in Condition 2?

Thank you,
Anna

**Comment by soniachothani** [comment]
Hi Anna, 

Yes - that is right. You can also confirm this by plotting counts across both conditions for some examples of upregulated/downregulated genes. DESeq2 has inbuilt plotting functions for genes: 

plotCounts(dds, gene, intgroup = "condition", normalized = TRUE..)
https://www.rdocumentation.org/packages/DESeq2/versions/1.12.3/topics/plotCounts

Hope this helps.

Thanks, 
Sonia
